# Generated by Django 4.2.1 on 2023-05-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saveKey', models.CharField(max_length=200)),
                ('operations', models.JSONField()),
                ('dataArray', models.JSONField()),
            ],
        ),
    ]
